comm_range:
  v2rsu: 100            # vehicle to RSU

simulation:
  ROU_FILE: '../osm_boston_common/osm.passenger.trips.xml' # route data (given a network, what paths can be taken?)
  NET_FILE: '../osm_boston_common/osm.net.xml' # network data (layout of the road)
  FCD_FILE: '../osm_boston_common/osm_fcd.xml' # floating car data (location and speed of every car in the network)
  # ROU_FILE: ''
  # NET_FILE: '../MonacoST/most.net.xml'
  # FCD_FILE: '../MonacoST/most_fcd.xml'
  # ROU_FILE: '../osm_london/osm.passenger.trips.xml'
  # NET_FILE: '../osm_london/osm.net.xml'
  # FCD_FILE: '../osm_london/london_fcd.xml'

  num_rsu: 5            # number of RSUs
  num_vc: 0 # number of stationary vehicular clouds (0, 2, 4, 6, 8, 10)
  vc_min_vehi: 5 # number of vehicles required to form a vehicular cloud
  maximum_rsu_accumulative_gradients: 10 # how many gradients does an RSU accumulate before updating the central server

neural_network:
  batch_size: 25
  epoch: 100
  # cifar lr = 0.0005
  learning_rate: 0.0005

seed: 99


# ********* frequently changed parameters ***************

dataset: 'pascalvoc' # mnist, cifar10, pascalvoc
num_training_data: 100 # 60000 for mnist, 16551 for pascalvoc
num_val_loss: 5000

aggregation_method: 'simplemean' # simplemean, cgc
attack: 'noattack'  # signflip, gaussian, bitflip, label, noattack
num_faulty_grads: 2

cgc_method: 'by-layer' # by-layer, multiply
